trainer:
  target: paintmind.engine.trainer.DiffusionTrainer
  params:
    num_epoch: 5260
    valid_size: 64
    lr: 3.5e-4
    lr_min: 5e-5
    warmup_steps: 2000
    warmup_lr_init: 1e-6
    decay_steps: 25000
    batch_size: 32
    num_workers: 32 
    pin_memory: True
    grad_accum_steps: 1
    mixed_precision: 'bf16'
    max_grad_norm: 3.0
    save_every: 3000
    sample_every: 3000
    result_folder: "output/debug"
    log_dir: "output/debug/logs"
    # result_folder: "output/tokenizer_dit_woof_5260ep_nested_enable_after_64slot_uniform_large"
    # log_dir: "output/tokenizer_dit_woof_5260ep_nested_enable_after_64slot_uniform_large/logs"
    model:
      # target: paintmind.stage1.vqmodel.TiTok
      target: paintmind.stage1.diffuse_slot.DiffuseSlot
      params:
        slot_dim: 8
        num_slots: 64
        num_samplers: 64
        sampler_dim: 8
        cond_method: 'token'
        dit_model: 'DiT-XL-2'
        vae: 'stabilityai/sd-vae-ft-ema'
        enable_nest: False
        enable_nest_after: 5100
        nest_rho: 0.03
        nest_dist: uniform
        use_encoder_rgb: True
        encoder: 'vit_base_patch16'
        enc_img_size: 256
        eval_fid: True
        fid_stats: 'fid_stats/adm_in256_stats.npz'

        ckpt_path: None
        # ckpt_path: "output/tokenizer_dit_woof_5260ep_nested_enable_after_64slot_uniform_large/models/step243000"

    dataset:
      # target: paintmind.utils.datasets.CoCoPanoptic
      target: paintmind.utils.datasets.ImageWoof
      params:
        root: /mnt/ceph_rbd/zbc/data/imagewoof/
        use_vae: True
        # root: /disk/scratch_fast/datasets/ImageNet1k/
        split: train
        img_size: 256
        scale: 0.8
    
