trainer:
  target: paintmind.engine.trainer.DiffusionTrainer
  params:
    num_epoch: 2350
    valid_size: 64
    lr: 7e-4
    lr_min: 1e-6
    warmup_steps: 4000
    warmup_lr_init: 1e-7
    decay_steps: 50000
    batch_size: 32
    num_workers: 8
    pin_memory: True
    grad_accum_steps: 2
    mixed_precision: 'bf16'
    max_grad_norm: 3.0
    save_every: 6000
    sample_every: 6005
    result_folder: "/mnt/ceph_rbd/mnt_pvc_vid_data/zbc/slot_ar/dit_imagenet100_pixart_control"
    log_dir: "/mnt/ceph_rbd/mnt_pvc_vid_data/zbc/slot_ar/dit_imagenet100_pixart_control/logs"
    # result_folder: "output/tokenizer_dit_woof_5260ep_nested_enable_after_64slot_uniform_large"
    # log_dir: "output/tokenizer_dit_woof_5260ep_nested_enable_after_64slot_uniform_large/logs"
    use_multi_epochs_dataloader: True
    making_cache: False
    cache_mode: False
    # latent_cache_file: "/disk/scratch_big/bingchen/slot_ar/save/imagenet100_latent_cache.pt"
    # latent_cache_file: "/mnt/ceph_rbd/zbc/imagenet100_latent_cache.pt"
    model:
      # target: paintmind.stage1.vqmodel.TiTok
      target: paintmind.stage1.diffuse_slot.DiffuseSlotPixArtControlNet
      params:
        slot_dim: 8
        num_slots: 128
        num_samplers: 128
        sampler_dim: 8
        enable_nest: False
        enable_nest_after: 50
        nest_rho: 0.03
        nest_dist: uniform
        use_encoder_rgb: True
        encoder: 'vit_base_patch16'
        enc_img_size: 256
        pixart_path: /mnt/ceph_rbd/zbc/pixart/
        reset_xattn: False

        ckpt_path: None
        # ckpt_path: "/mnt/ceph_rbd/mnt_pvc_vid_data/zbc/slot_ar/dit_imagenet100_pixart/models/step6000"
        # ckpt_path: "/mnt/ceph_rbd/mnt_pvc_vid_data/zbc/slot_ar/dit_imagenet100_ready_bs72/models/step660000"
        # ckpt_path: "/mnt/ceph_rbd/zbc/step132000"
        # ckpt_path: "output/dit_imagenet100_850ep_nest_after50/models/step432000"
        # ckpt_path: "/mnt/ceph_rbd/mnt_pvc_vid_data/zbc/slot_ar/dit_imagenet100_ready/step428000"
        # ckpt_path: "output/dit_5560_ln/models/step780000"
        # ckpt_path: "output/dit_woof_3460ep_enable_after_3400ep_noln/models/step365000"
        # ckpt_path: "output/tokenizer_dit_woof_5260ep_nested_enable_after_64slot_uniform_large/models/step243000"

        # pretrained_dit: /mnt/ceph_rbd/zbc/.cache/DiT-XL-2-256x256.pt
        
        use_vq: False
        # use_lfq: False
        # codebook_size: 65536
        # code_dim: 8
        code_beta: 0.1
        # vq_norm: False

    dataset:
      # target: paintmind.utils.datasets.CoCoPanoptic
      target: paintmind.utils.datasets.ImageWoof
      # target: paintmind.utils.datasets.ImageNet
      params:
        # root: /mnt/ceph_rbd/zbc/data/imagewoof/
        use_vae: True
        root: /mnt/ceph_rbd/zbc/data/imagenet100/
        cache_mode: False
        # cache_latent_file: "/mnt/ceph_rbd/zbc/imagenet100_latent_cache.pt"
        split: train
        img_size: 256
        scale: 0.8
    
